
// This file has been generated by the GUI designer. Do not modify.
namespace Sudoku
{
	public partial class poziom_wybór
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Sudoku.poziom_wybór
			this.Name = "Sudoku.poziom_wybór";
			this.Title = global::Mono.Unix.Catalog.GetString ("poziom_wybór");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
