
// This file has been generated by the GUI designer. Do not modify.
namespace Sudoku
{
	public partial class MainWindow
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Button generate_sud;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Sudoku.MainWindow
			this.Name = "Sudoku.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Sudoku.MainWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.generate_sud = new global::Gtk.Button ();
			this.generate_sud.WidthRequest = 123;
			this.generate_sud.HeightRequest = 72;
			this.generate_sud.CanFocus = true;
			this.generate_sud.Name = "generate_sud";
			this.generate_sud.UseUnderline = true;
			this.generate_sud.Label = global::Mono.Unix.Catalog.GetString ("Generuj sudoku");
			this.fixed1.Add (this.generate_sud);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.generate_sud]));
			w1.X = 114;
			w1.Y = 48;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 349;
			this.DefaultHeight = 176;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
