
// This file has been generated by the GUI designer. Do not modify.
namespace Sudoku
{
	public partial class wybierz_poziom
	{
		private global::Gtk.Fixed fixed4;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Button button2;
		
		private global::Gtk.Button button3;
		
		private global::Gtk.Button button4;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Sudoku.wybierz_poziom
			this.WidthRequest = 450;
			this.HeightRequest = 380;
			this.Name = "Sudoku.wybierz_poziom";
			this.Title = global::Mono.Unix.Catalog.GetString ("wybierz_poziom");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Container child Sudoku.wybierz_poziom.Gtk.Container+ContainerChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.WidthRequest = 300;
			this.label3.HeightRequest = 50;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Witamy w Sudoku! Wybierz poziom:");
			this.fixed4.Add (this.label3);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label3]));
			w1.X = 90;
			w1.Y = 43;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button ();
			this.button2.HeightRequest = 50;
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Łatwy (25 pól zakrytych)");
			this.fixed4.Add (this.button2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.button2]));
			w2.X = 155;
			w2.Y = 94;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.button3 = new global::Gtk.Button ();
			this.button3.HeightRequest = 50;
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("Średni ( 40 pól zakrytych)");
			this.fixed4.Add (this.button3);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.button3]));
			w3.X = 153;
			w3.Y = 159;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.button4 = new global::Gtk.Button ();
			this.button4.HeightRequest = 50;
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString ("Trudny (55 pól zakrytych)");
			this.fixed4.Add (this.button4);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.button4]));
			w4.X = 153;
			w4.Y = 223;
			this.Add (this.fixed4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 474;
			this.DefaultHeight = 450;
			this.Show ();
			this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
			this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
			this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
		}
	}
}
