
// This file has been generated by the GUI designer. Do not modify.
namespace Sudoku
{
	public partial class Plansza
	{
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Entry entry1;
		
		private global::Gtk.Entry entry10;
		
		private global::Gtk.Entry entry11;
		
		private global::Gtk.Entry entry12;
		
		private global::Gtk.Entry entry13;
		
		private global::Gtk.Entry entry14;
		
		private global::Gtk.Entry entry15;
		
		private global::Gtk.Entry entry16;
		
		private global::Gtk.Entry entry17;
		
		private global::Gtk.Entry entry18;
		
		private global::Gtk.Entry entry19;
		
		private global::Gtk.Entry entry2;
		
		private global::Gtk.Entry entry20;
		
		private global::Gtk.Entry entry21;
		
		private global::Gtk.Entry entry22;
		
		private global::Gtk.Entry entry23;
		
		private global::Gtk.Entry entry24;
		
		private global::Gtk.Entry entry25;
		
		private global::Gtk.Entry entry26;
		
		private global::Gtk.Entry entry27;
		
		private global::Gtk.Entry entry28;
		
		private global::Gtk.Entry entry29;
		
		private global::Gtk.Entry entry3;
		
		private global::Gtk.Entry entry30;
		
		private global::Gtk.Entry entry31;
		
		private global::Gtk.Entry entry32;
		
		private global::Gtk.Entry entry33;
		
		private global::Gtk.Entry entry34;
		
		private global::Gtk.Entry entry35;
		
		private global::Gtk.Entry entry36;
		
		private global::Gtk.Entry entry37;
		
		private global::Gtk.Entry entry38;
		
		private global::Gtk.Entry entry39;
		
		private global::Gtk.Entry entry4;
		
		private global::Gtk.Entry entry40;
		
		private global::Gtk.Entry entry41;
		
		private global::Gtk.Entry entry42;
		
		private global::Gtk.Entry entry43;
		
		private global::Gtk.Entry entry44;
		
		private global::Gtk.Entry entry45;
		
		private global::Gtk.Entry entry46;
		
		private global::Gtk.Entry entry47;
		
		private global::Gtk.Entry entry48;
		
		private global::Gtk.Entry entry49;
		
		private global::Gtk.Entry entry5;
		
		private global::Gtk.Entry entry50;
		
		private global::Gtk.Entry entry51;
		
		private global::Gtk.Entry entry52;
		
		private global::Gtk.Entry entry53;
		
		private global::Gtk.Entry entry54;
		
		private global::Gtk.Entry entry55;
		
		private global::Gtk.Entry entry56;
		
		private global::Gtk.Entry entry57;
		
		private global::Gtk.Entry entry58;
		
		private global::Gtk.Entry entry59;
		
		private global::Gtk.Entry entry6;
		
		private global::Gtk.Entry entry60;
		
		private global::Gtk.Entry entry61;
		
		private global::Gtk.Entry entry62;
		
		private global::Gtk.Entry entry63;
		
		private global::Gtk.Entry entry64;
		
		private global::Gtk.Entry entry65;
		
		private global::Gtk.Entry entry66;
		
		private global::Gtk.Entry entry67;
		
		private global::Gtk.Entry entry68;
		
		private global::Gtk.Entry entry69;
		
		private global::Gtk.Entry entry7;
		
		private global::Gtk.Entry entry70;
		
		private global::Gtk.Entry entry71;
		
		private global::Gtk.Entry entry72;
		
		private global::Gtk.Entry entry73;
		
		private global::Gtk.Entry entry74;
		
		private global::Gtk.Entry entry75;
		
		private global::Gtk.Entry entry76;
		
		private global::Gtk.Entry entry77;
		
		private global::Gtk.Entry entry78;
		
		private global::Gtk.Entry entry79;
		
		private global::Gtk.Entry entry8;
		
		private global::Gtk.Entry entry80;
		
		private global::Gtk.Entry entry81;
		
		private global::Gtk.Entry entry9;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Sudoku.Plansza
			this.Name = "Sudoku.Plansza";
			this.Title = global::Mono.Unix.Catalog.GetString ("Plansza");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Sudoku.Plansza.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.WidthRequest = 600;
			this.fixed2.HeightRequest = 600;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.table1 = new global::Gtk.Table (((uint)(9)), ((uint)(9)), false);
			this.table1.WidthRequest = 400;
			this.table1.HeightRequest = 400;
			this.table1.Name = "table1";
			this.table1.BorderWidth = ((uint)(3));
			// Container child table1.Gtk.Table+TableChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.WidthRequest = 45;
			this.entry1.HeightRequest = 45;
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.table1.Add (this.entry1);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry1]));
			w1.XOptions = ((global::Gtk.AttachOptions)(0));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry10 = new global::Gtk.Entry ();
			this.entry10.WidthRequest = 45;
			this.entry10.HeightRequest = 45;
			this.entry10.CanFocus = true;
			this.entry10.Name = "entry10";
			this.entry10.IsEditable = true;
			this.entry10.InvisibleChar = '•';
			this.table1.Add (this.entry10);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry10]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(0));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry11 = new global::Gtk.Entry ();
			this.entry11.WidthRequest = 45;
			this.entry11.HeightRequest = 45;
			this.entry11.CanFocus = true;
			this.entry11.Name = "entry11";
			this.entry11.IsEditable = true;
			this.entry11.InvisibleChar = '•';
			this.table1.Add (this.entry11);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry11]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry12 = new global::Gtk.Entry ();
			this.entry12.WidthRequest = 45;
			this.entry12.HeightRequest = 45;
			this.entry12.CanFocus = true;
			this.entry12.Name = "entry12";
			this.entry12.IsEditable = true;
			this.entry12.InvisibleChar = '•';
			this.table1.Add (this.entry12);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry12]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry13 = new global::Gtk.Entry ();
			this.entry13.WidthRequest = 45;
			this.entry13.HeightRequest = 45;
			this.entry13.CanFocus = true;
			this.entry13.Name = "entry13";
			this.entry13.IsEditable = true;
			this.entry13.InvisibleChar = '•';
			this.table1.Add (this.entry13);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry13]));
			w5.TopAttach = ((uint)(3));
			w5.BottomAttach = ((uint)(4));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry14 = new global::Gtk.Entry ();
			this.entry14.WidthRequest = 45;
			this.entry14.HeightRequest = 45;
			this.entry14.CanFocus = true;
			this.entry14.Name = "entry14";
			this.entry14.IsEditable = true;
			this.entry14.InvisibleChar = '•';
			this.table1.Add (this.entry14);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry14]));
			w6.TopAttach = ((uint)(4));
			w6.BottomAttach = ((uint)(5));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry15 = new global::Gtk.Entry ();
			this.entry15.WidthRequest = 45;
			this.entry15.HeightRequest = 45;
			this.entry15.CanFocus = true;
			this.entry15.Name = "entry15";
			this.entry15.IsEditable = true;
			this.entry15.InvisibleChar = '•';
			this.table1.Add (this.entry15);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry15]));
			w7.TopAttach = ((uint)(5));
			w7.BottomAttach = ((uint)(6));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry16 = new global::Gtk.Entry ();
			this.entry16.WidthRequest = 45;
			this.entry16.HeightRequest = 45;
			this.entry16.CanFocus = true;
			this.entry16.Name = "entry16";
			this.entry16.IsEditable = true;
			this.entry16.InvisibleChar = '•';
			this.table1.Add (this.entry16);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry16]));
			w8.TopAttach = ((uint)(6));
			w8.BottomAttach = ((uint)(7));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry17 = new global::Gtk.Entry ();
			this.entry17.WidthRequest = 45;
			this.entry17.HeightRequest = 45;
			this.entry17.CanFocus = true;
			this.entry17.Name = "entry17";
			this.entry17.IsEditable = true;
			this.entry17.InvisibleChar = '•';
			this.table1.Add (this.entry17);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry17]));
			w9.TopAttach = ((uint)(7));
			w9.BottomAttach = ((uint)(8));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry18 = new global::Gtk.Entry ();
			this.entry18.WidthRequest = 45;
			this.entry18.HeightRequest = 45;
			this.entry18.CanFocus = true;
			this.entry18.Name = "entry18";
			this.entry18.IsEditable = true;
			this.entry18.InvisibleChar = '•';
			this.table1.Add (this.entry18);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry18]));
			w10.TopAttach = ((uint)(8));
			w10.BottomAttach = ((uint)(9));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry19 = new global::Gtk.Entry ();
			this.entry19.WidthRequest = 45;
			this.entry19.HeightRequest = 45;
			this.entry19.CanFocus = true;
			this.entry19.Name = "entry19";
			this.entry19.IsEditable = true;
			this.entry19.InvisibleChar = '•';
			this.table1.Add (this.entry19);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry19]));
			w11.LeftAttach = ((uint)(2));
			w11.RightAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry2 = new global::Gtk.Entry ();
			this.entry2.WidthRequest = 45;
			this.entry2.HeightRequest = 45;
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '•';
			this.table1.Add (this.entry2);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry2]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry20 = new global::Gtk.Entry ();
			this.entry20.WidthRequest = 45;
			this.entry20.HeightRequest = 45;
			this.entry20.CanFocus = true;
			this.entry20.Name = "entry20";
			this.entry20.IsEditable = true;
			this.entry20.InvisibleChar = '•';
			this.table1.Add (this.entry20);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry20]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(2));
			w13.RightAttach = ((uint)(3));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry21 = new global::Gtk.Entry ();
			this.entry21.WidthRequest = 45;
			this.entry21.HeightRequest = 45;
			this.entry21.CanFocus = true;
			this.entry21.Name = "entry21";
			this.entry21.IsEditable = true;
			this.entry21.InvisibleChar = '•';
			this.table1.Add (this.entry21);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry21]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.LeftAttach = ((uint)(2));
			w14.RightAttach = ((uint)(3));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry22 = new global::Gtk.Entry ();
			this.entry22.WidthRequest = 45;
			this.entry22.HeightRequest = 45;
			this.entry22.CanFocus = true;
			this.entry22.Name = "entry22";
			this.entry22.IsEditable = true;
			this.entry22.InvisibleChar = '•';
			this.table1.Add (this.entry22);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry22]));
			w15.TopAttach = ((uint)(3));
			w15.BottomAttach = ((uint)(4));
			w15.LeftAttach = ((uint)(2));
			w15.RightAttach = ((uint)(3));
			w15.XOptions = ((global::Gtk.AttachOptions)(0));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry23 = new global::Gtk.Entry ();
			this.entry23.WidthRequest = 45;
			this.entry23.HeightRequest = 45;
			this.entry23.CanFocus = true;
			this.entry23.Name = "entry23";
			this.entry23.IsEditable = true;
			this.entry23.InvisibleChar = '•';
			this.table1.Add (this.entry23);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry23]));
			w16.TopAttach = ((uint)(4));
			w16.BottomAttach = ((uint)(5));
			w16.LeftAttach = ((uint)(2));
			w16.RightAttach = ((uint)(3));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry24 = new global::Gtk.Entry ();
			this.entry24.WidthRequest = 45;
			this.entry24.HeightRequest = 45;
			this.entry24.CanFocus = true;
			this.entry24.Name = "entry24";
			this.entry24.IsEditable = true;
			this.entry24.InvisibleChar = '•';
			this.table1.Add (this.entry24);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry24]));
			w17.TopAttach = ((uint)(5));
			w17.BottomAttach = ((uint)(6));
			w17.LeftAttach = ((uint)(2));
			w17.RightAttach = ((uint)(3));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry25 = new global::Gtk.Entry ();
			this.entry25.WidthRequest = 45;
			this.entry25.HeightRequest = 45;
			this.entry25.CanFocus = true;
			this.entry25.Name = "entry25";
			this.entry25.IsEditable = true;
			this.entry25.InvisibleChar = '•';
			this.table1.Add (this.entry25);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry25]));
			w18.TopAttach = ((uint)(6));
			w18.BottomAttach = ((uint)(7));
			w18.LeftAttach = ((uint)(2));
			w18.RightAttach = ((uint)(3));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry26 = new global::Gtk.Entry ();
			this.entry26.WidthRequest = 45;
			this.entry26.HeightRequest = 45;
			this.entry26.CanFocus = true;
			this.entry26.Name = "entry26";
			this.entry26.IsEditable = true;
			this.entry26.InvisibleChar = '•';
			this.table1.Add (this.entry26);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry26]));
			w19.TopAttach = ((uint)(7));
			w19.BottomAttach = ((uint)(8));
			w19.LeftAttach = ((uint)(2));
			w19.RightAttach = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry27 = new global::Gtk.Entry ();
			this.entry27.WidthRequest = 45;
			this.entry27.HeightRequest = 45;
			this.entry27.CanFocus = true;
			this.entry27.Name = "entry27";
			this.entry27.IsEditable = true;
			this.entry27.InvisibleChar = '•';
			this.table1.Add (this.entry27);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry27]));
			w20.TopAttach = ((uint)(8));
			w20.BottomAttach = ((uint)(9));
			w20.LeftAttach = ((uint)(2));
			w20.RightAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry28 = new global::Gtk.Entry ();
			this.entry28.WidthRequest = 45;
			this.entry28.HeightRequest = 45;
			this.entry28.CanFocus = true;
			this.entry28.Name = "entry28";
			this.entry28.IsEditable = true;
			this.entry28.InvisibleChar = '•';
			this.table1.Add (this.entry28);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry28]));
			w21.LeftAttach = ((uint)(3));
			w21.RightAttach = ((uint)(4));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry29 = new global::Gtk.Entry ();
			this.entry29.WidthRequest = 45;
			this.entry29.HeightRequest = 45;
			this.entry29.CanFocus = true;
			this.entry29.Name = "entry29";
			this.entry29.IsEditable = true;
			this.entry29.InvisibleChar = '•';
			this.table1.Add (this.entry29);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry29]));
			w22.TopAttach = ((uint)(1));
			w22.BottomAttach = ((uint)(2));
			w22.LeftAttach = ((uint)(3));
			w22.RightAttach = ((uint)(4));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry3 = new global::Gtk.Entry ();
			this.entry3.WidthRequest = 45;
			this.entry3.HeightRequest = 45;
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '•';
			this.table1.Add (this.entry3);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry3]));
			w23.TopAttach = ((uint)(2));
			w23.BottomAttach = ((uint)(3));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry30 = new global::Gtk.Entry ();
			this.entry30.WidthRequest = 45;
			this.entry30.HeightRequest = 45;
			this.entry30.CanFocus = true;
			this.entry30.Name = "entry30";
			this.entry30.IsEditable = true;
			this.entry30.InvisibleChar = '•';
			this.table1.Add (this.entry30);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry30]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.LeftAttach = ((uint)(3));
			w24.RightAttach = ((uint)(4));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry31 = new global::Gtk.Entry ();
			this.entry31.WidthRequest = 45;
			this.entry31.HeightRequest = 45;
			this.entry31.CanFocus = true;
			this.entry31.Name = "entry31";
			this.entry31.IsEditable = true;
			this.entry31.InvisibleChar = '•';
			this.table1.Add (this.entry31);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry31]));
			w25.TopAttach = ((uint)(3));
			w25.BottomAttach = ((uint)(4));
			w25.LeftAttach = ((uint)(3));
			w25.RightAttach = ((uint)(4));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry32 = new global::Gtk.Entry ();
			this.entry32.WidthRequest = 45;
			this.entry32.HeightRequest = 45;
			this.entry32.CanFocus = true;
			this.entry32.Name = "entry32";
			this.entry32.IsEditable = true;
			this.entry32.InvisibleChar = '•';
			this.table1.Add (this.entry32);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry32]));
			w26.TopAttach = ((uint)(4));
			w26.BottomAttach = ((uint)(5));
			w26.LeftAttach = ((uint)(3));
			w26.RightAttach = ((uint)(4));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry33 = new global::Gtk.Entry ();
			this.entry33.WidthRequest = 45;
			this.entry33.HeightRequest = 45;
			this.entry33.CanFocus = true;
			this.entry33.Name = "entry33";
			this.entry33.IsEditable = true;
			this.entry33.InvisibleChar = '•';
			this.table1.Add (this.entry33);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry33]));
			w27.TopAttach = ((uint)(5));
			w27.BottomAttach = ((uint)(6));
			w27.LeftAttach = ((uint)(3));
			w27.RightAttach = ((uint)(4));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry34 = new global::Gtk.Entry ();
			this.entry34.WidthRequest = 45;
			this.entry34.HeightRequest = 45;
			this.entry34.CanFocus = true;
			this.entry34.Name = "entry34";
			this.entry34.IsEditable = true;
			this.entry34.InvisibleChar = '•';
			this.table1.Add (this.entry34);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry34]));
			w28.TopAttach = ((uint)(6));
			w28.BottomAttach = ((uint)(7));
			w28.LeftAttach = ((uint)(3));
			w28.RightAttach = ((uint)(4));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry35 = new global::Gtk.Entry ();
			this.entry35.WidthRequest = 45;
			this.entry35.HeightRequest = 45;
			this.entry35.CanFocus = true;
			this.entry35.Name = "entry35";
			this.entry35.IsEditable = true;
			this.entry35.InvisibleChar = '•';
			this.table1.Add (this.entry35);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry35]));
			w29.TopAttach = ((uint)(7));
			w29.BottomAttach = ((uint)(8));
			w29.LeftAttach = ((uint)(3));
			w29.RightAttach = ((uint)(4));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry36 = new global::Gtk.Entry ();
			this.entry36.WidthRequest = 45;
			this.entry36.HeightRequest = 45;
			this.entry36.CanFocus = true;
			this.entry36.Name = "entry36";
			this.entry36.IsEditable = true;
			this.entry36.InvisibleChar = '•';
			this.table1.Add (this.entry36);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry36]));
			w30.TopAttach = ((uint)(8));
			w30.BottomAttach = ((uint)(9));
			w30.LeftAttach = ((uint)(3));
			w30.RightAttach = ((uint)(4));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry37 = new global::Gtk.Entry ();
			this.entry37.WidthRequest = 45;
			this.entry37.HeightRequest = 45;
			this.entry37.CanFocus = true;
			this.entry37.Name = "entry37";
			this.entry37.IsEditable = true;
			this.entry37.InvisibleChar = '•';
			this.table1.Add (this.entry37);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry37]));
			w31.LeftAttach = ((uint)(4));
			w31.RightAttach = ((uint)(5));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry38 = new global::Gtk.Entry ();
			this.entry38.WidthRequest = 45;
			this.entry38.HeightRequest = 45;
			this.entry38.CanFocus = true;
			this.entry38.Name = "entry38";
			this.entry38.IsEditable = true;
			this.entry38.InvisibleChar = '•';
			this.table1.Add (this.entry38);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry38]));
			w32.TopAttach = ((uint)(1));
			w32.BottomAttach = ((uint)(2));
			w32.LeftAttach = ((uint)(4));
			w32.RightAttach = ((uint)(5));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry39 = new global::Gtk.Entry ();
			this.entry39.WidthRequest = 45;
			this.entry39.HeightRequest = 45;
			this.entry39.CanFocus = true;
			this.entry39.Name = "entry39";
			this.entry39.IsEditable = true;
			this.entry39.InvisibleChar = '•';
			this.table1.Add (this.entry39);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry39]));
			w33.TopAttach = ((uint)(2));
			w33.BottomAttach = ((uint)(3));
			w33.LeftAttach = ((uint)(4));
			w33.RightAttach = ((uint)(5));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry4 = new global::Gtk.Entry ();
			this.entry4.WidthRequest = 45;
			this.entry4.HeightRequest = 45;
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '•';
			this.table1.Add (this.entry4);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry4]));
			w34.TopAttach = ((uint)(3));
			w34.BottomAttach = ((uint)(4));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry40 = new global::Gtk.Entry ();
			this.entry40.WidthRequest = 45;
			this.entry40.HeightRequest = 45;
			this.entry40.CanFocus = true;
			this.entry40.Name = "entry40";
			this.entry40.IsEditable = true;
			this.entry40.InvisibleChar = '•';
			this.table1.Add (this.entry40);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry40]));
			w35.TopAttach = ((uint)(3));
			w35.BottomAttach = ((uint)(4));
			w35.LeftAttach = ((uint)(4));
			w35.RightAttach = ((uint)(5));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry41 = new global::Gtk.Entry ();
			this.entry41.WidthRequest = 45;
			this.entry41.HeightRequest = 45;
			this.entry41.CanFocus = true;
			this.entry41.Name = "entry41";
			this.entry41.IsEditable = true;
			this.entry41.InvisibleChar = '•';
			this.table1.Add (this.entry41);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry41]));
			w36.TopAttach = ((uint)(4));
			w36.BottomAttach = ((uint)(5));
			w36.LeftAttach = ((uint)(4));
			w36.RightAttach = ((uint)(5));
			w36.XOptions = ((global::Gtk.AttachOptions)(4));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry42 = new global::Gtk.Entry ();
			this.entry42.WidthRequest = 45;
			this.entry42.HeightRequest = 45;
			this.entry42.CanFocus = true;
			this.entry42.Name = "entry42";
			this.entry42.IsEditable = true;
			this.entry42.InvisibleChar = '•';
			this.table1.Add (this.entry42);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry42]));
			w37.TopAttach = ((uint)(5));
			w37.BottomAttach = ((uint)(6));
			w37.LeftAttach = ((uint)(4));
			w37.RightAttach = ((uint)(5));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry43 = new global::Gtk.Entry ();
			this.entry43.WidthRequest = 45;
			this.entry43.HeightRequest = 45;
			this.entry43.CanFocus = true;
			this.entry43.Name = "entry43";
			this.entry43.IsEditable = true;
			this.entry43.InvisibleChar = '•';
			this.table1.Add (this.entry43);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry43]));
			w38.TopAttach = ((uint)(6));
			w38.BottomAttach = ((uint)(7));
			w38.LeftAttach = ((uint)(4));
			w38.RightAttach = ((uint)(5));
			w38.XOptions = ((global::Gtk.AttachOptions)(4));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry44 = new global::Gtk.Entry ();
			this.entry44.WidthRequest = 45;
			this.entry44.HeightRequest = 45;
			this.entry44.CanFocus = true;
			this.entry44.Name = "entry44";
			this.entry44.IsEditable = true;
			this.entry44.InvisibleChar = '•';
			this.table1.Add (this.entry44);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry44]));
			w39.TopAttach = ((uint)(7));
			w39.BottomAttach = ((uint)(8));
			w39.LeftAttach = ((uint)(4));
			w39.RightAttach = ((uint)(5));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry45 = new global::Gtk.Entry ();
			this.entry45.WidthRequest = 45;
			this.entry45.HeightRequest = 45;
			this.entry45.CanFocus = true;
			this.entry45.Name = "entry45";
			this.entry45.IsEditable = true;
			this.entry45.InvisibleChar = '•';
			this.table1.Add (this.entry45);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry45]));
			w40.TopAttach = ((uint)(8));
			w40.BottomAttach = ((uint)(9));
			w40.LeftAttach = ((uint)(4));
			w40.RightAttach = ((uint)(5));
			w40.XOptions = ((global::Gtk.AttachOptions)(0));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry46 = new global::Gtk.Entry ();
			this.entry46.WidthRequest = 45;
			this.entry46.HeightRequest = 45;
			this.entry46.CanFocus = true;
			this.entry46.Name = "entry46";
			this.entry46.IsEditable = true;
			this.entry46.InvisibleChar = '•';
			this.table1.Add (this.entry46);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry46]));
			w41.LeftAttach = ((uint)(5));
			w41.RightAttach = ((uint)(6));
			w41.XOptions = ((global::Gtk.AttachOptions)(0));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry47 = new global::Gtk.Entry ();
			this.entry47.WidthRequest = 45;
			this.entry47.HeightRequest = 45;
			this.entry47.CanFocus = true;
			this.entry47.Name = "entry47";
			this.entry47.IsEditable = true;
			this.entry47.InvisibleChar = '•';
			this.table1.Add (this.entry47);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry47]));
			w42.LeftAttach = ((uint)(6));
			w42.RightAttach = ((uint)(7));
			w42.XOptions = ((global::Gtk.AttachOptions)(0));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry48 = new global::Gtk.Entry ();
			this.entry48.WidthRequest = 45;
			this.entry48.HeightRequest = 45;
			this.entry48.CanFocus = true;
			this.entry48.Name = "entry48";
			this.entry48.IsEditable = true;
			this.entry48.InvisibleChar = '•';
			this.table1.Add (this.entry48);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry48]));
			w43.LeftAttach = ((uint)(7));
			w43.RightAttach = ((uint)(8));
			w43.XOptions = ((global::Gtk.AttachOptions)(0));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry49 = new global::Gtk.Entry ();
			this.entry49.WidthRequest = 45;
			this.entry49.HeightRequest = 45;
			this.entry49.CanFocus = true;
			this.entry49.Name = "entry49";
			this.entry49.IsEditable = true;
			this.entry49.InvisibleChar = '•';
			this.table1.Add (this.entry49);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry49]));
			w44.LeftAttach = ((uint)(8));
			w44.RightAttach = ((uint)(9));
			w44.XOptions = ((global::Gtk.AttachOptions)(0));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry5 = new global::Gtk.Entry ();
			this.entry5.WidthRequest = 45;
			this.entry5.HeightRequest = 45;
			this.entry5.CanFocus = true;
			this.entry5.Name = "entry5";
			this.entry5.IsEditable = true;
			this.entry5.InvisibleChar = '•';
			this.table1.Add (this.entry5);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry5]));
			w45.TopAttach = ((uint)(4));
			w45.BottomAttach = ((uint)(5));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry50 = new global::Gtk.Entry ();
			this.entry50.WidthRequest = 45;
			this.entry50.HeightRequest = 45;
			this.entry50.CanFocus = true;
			this.entry50.Name = "entry50";
			this.entry50.IsEditable = true;
			this.entry50.InvisibleChar = '•';
			this.table1.Add (this.entry50);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry50]));
			w46.TopAttach = ((uint)(1));
			w46.BottomAttach = ((uint)(2));
			w46.LeftAttach = ((uint)(5));
			w46.RightAttach = ((uint)(6));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry51 = new global::Gtk.Entry ();
			this.entry51.WidthRequest = 45;
			this.entry51.HeightRequest = 45;
			this.entry51.CanFocus = true;
			this.entry51.Name = "entry51";
			this.entry51.IsEditable = true;
			this.entry51.InvisibleChar = '•';
			this.table1.Add (this.entry51);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry51]));
			w47.TopAttach = ((uint)(2));
			w47.BottomAttach = ((uint)(3));
			w47.LeftAttach = ((uint)(5));
			w47.RightAttach = ((uint)(6));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry52 = new global::Gtk.Entry ();
			this.entry52.WidthRequest = 45;
			this.entry52.HeightRequest = 45;
			this.entry52.CanFocus = true;
			this.entry52.Name = "entry52";
			this.entry52.IsEditable = true;
			this.entry52.InvisibleChar = '•';
			this.table1.Add (this.entry52);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry52]));
			w48.TopAttach = ((uint)(3));
			w48.BottomAttach = ((uint)(4));
			w48.LeftAttach = ((uint)(5));
			w48.RightAttach = ((uint)(6));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry53 = new global::Gtk.Entry ();
			this.entry53.WidthRequest = 45;
			this.entry53.HeightRequest = 45;
			this.entry53.CanFocus = true;
			this.entry53.Name = "entry53";
			this.entry53.IsEditable = true;
			this.entry53.InvisibleChar = '•';
			this.table1.Add (this.entry53);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry53]));
			w49.TopAttach = ((uint)(4));
			w49.BottomAttach = ((uint)(5));
			w49.LeftAttach = ((uint)(5));
			w49.RightAttach = ((uint)(6));
			w49.XOptions = ((global::Gtk.AttachOptions)(4));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry54 = new global::Gtk.Entry ();
			this.entry54.WidthRequest = 45;
			this.entry54.HeightRequest = 45;
			this.entry54.CanFocus = true;
			this.entry54.Name = "entry54";
			this.entry54.IsEditable = true;
			this.entry54.InvisibleChar = '•';
			this.table1.Add (this.entry54);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry54]));
			w50.TopAttach = ((uint)(5));
			w50.BottomAttach = ((uint)(6));
			w50.LeftAttach = ((uint)(5));
			w50.RightAttach = ((uint)(6));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry55 = new global::Gtk.Entry ();
			this.entry55.WidthRequest = 45;
			this.entry55.HeightRequest = 45;
			this.entry55.CanFocus = true;
			this.entry55.Name = "entry55";
			this.entry55.IsEditable = true;
			this.entry55.InvisibleChar = '•';
			this.table1.Add (this.entry55);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry55]));
			w51.TopAttach = ((uint)(6));
			w51.BottomAttach = ((uint)(7));
			w51.LeftAttach = ((uint)(5));
			w51.RightAttach = ((uint)(6));
			w51.XOptions = ((global::Gtk.AttachOptions)(4));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry56 = new global::Gtk.Entry ();
			this.entry56.WidthRequest = 45;
			this.entry56.HeightRequest = 45;
			this.entry56.CanFocus = true;
			this.entry56.Name = "entry56";
			this.entry56.IsEditable = true;
			this.entry56.InvisibleChar = '•';
			this.table1.Add (this.entry56);
			global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry56]));
			w52.TopAttach = ((uint)(7));
			w52.BottomAttach = ((uint)(8));
			w52.LeftAttach = ((uint)(5));
			w52.RightAttach = ((uint)(6));
			w52.XOptions = ((global::Gtk.AttachOptions)(4));
			w52.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry57 = new global::Gtk.Entry ();
			this.entry57.WidthRequest = 45;
			this.entry57.HeightRequest = 45;
			this.entry57.CanFocus = true;
			this.entry57.Name = "entry57";
			this.entry57.IsEditable = true;
			this.entry57.InvisibleChar = '•';
			this.table1.Add (this.entry57);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry57]));
			w53.TopAttach = ((uint)(8));
			w53.BottomAttach = ((uint)(9));
			w53.LeftAttach = ((uint)(5));
			w53.RightAttach = ((uint)(6));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry58 = new global::Gtk.Entry ();
			this.entry58.WidthRequest = 45;
			this.entry58.HeightRequest = 45;
			this.entry58.CanFocus = true;
			this.entry58.Name = "entry58";
			this.entry58.IsEditable = true;
			this.entry58.InvisibleChar = '•';
			this.table1.Add (this.entry58);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry58]));
			w54.TopAttach = ((uint)(1));
			w54.BottomAttach = ((uint)(2));
			w54.LeftAttach = ((uint)(6));
			w54.RightAttach = ((uint)(7));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry59 = new global::Gtk.Entry ();
			this.entry59.WidthRequest = 45;
			this.entry59.HeightRequest = 45;
			this.entry59.CanFocus = true;
			this.entry59.Name = "entry59";
			this.entry59.IsEditable = true;
			this.entry59.InvisibleChar = '•';
			this.table1.Add (this.entry59);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry59]));
			w55.TopAttach = ((uint)(2));
			w55.BottomAttach = ((uint)(3));
			w55.LeftAttach = ((uint)(6));
			w55.RightAttach = ((uint)(7));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry6 = new global::Gtk.Entry ();
			this.entry6.WidthRequest = 45;
			this.entry6.HeightRequest = 45;
			this.entry6.CanFocus = true;
			this.entry6.Name = "entry6";
			this.entry6.IsEditable = true;
			this.entry6.InvisibleChar = '•';
			this.table1.Add (this.entry6);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry6]));
			w56.TopAttach = ((uint)(5));
			w56.BottomAttach = ((uint)(6));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry60 = new global::Gtk.Entry ();
			this.entry60.WidthRequest = 45;
			this.entry60.HeightRequest = 45;
			this.entry60.CanFocus = true;
			this.entry60.Name = "entry60";
			this.entry60.IsEditable = true;
			this.entry60.InvisibleChar = '•';
			this.table1.Add (this.entry60);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry60]));
			w57.TopAttach = ((uint)(3));
			w57.BottomAttach = ((uint)(4));
			w57.LeftAttach = ((uint)(6));
			w57.RightAttach = ((uint)(7));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry61 = new global::Gtk.Entry ();
			this.entry61.WidthRequest = 45;
			this.entry61.HeightRequest = 45;
			this.entry61.CanFocus = true;
			this.entry61.Name = "entry61";
			this.entry61.IsEditable = true;
			this.entry61.InvisibleChar = '•';
			this.table1.Add (this.entry61);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry61]));
			w58.TopAttach = ((uint)(4));
			w58.BottomAttach = ((uint)(5));
			w58.LeftAttach = ((uint)(6));
			w58.RightAttach = ((uint)(7));
			w58.XOptions = ((global::Gtk.AttachOptions)(4));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry62 = new global::Gtk.Entry ();
			this.entry62.WidthRequest = 45;
			this.entry62.HeightRequest = 45;
			this.entry62.CanFocus = true;
			this.entry62.Name = "entry62";
			this.entry62.IsEditable = true;
			this.entry62.InvisibleChar = '•';
			this.table1.Add (this.entry62);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry62]));
			w59.TopAttach = ((uint)(5));
			w59.BottomAttach = ((uint)(6));
			w59.LeftAttach = ((uint)(6));
			w59.RightAttach = ((uint)(7));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry63 = new global::Gtk.Entry ();
			this.entry63.WidthRequest = 45;
			this.entry63.HeightRequest = 45;
			this.entry63.CanFocus = true;
			this.entry63.Name = "entry63";
			this.entry63.IsEditable = true;
			this.entry63.InvisibleChar = '•';
			this.table1.Add (this.entry63);
			global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry63]));
			w60.TopAttach = ((uint)(6));
			w60.BottomAttach = ((uint)(7));
			w60.LeftAttach = ((uint)(6));
			w60.RightAttach = ((uint)(7));
			w60.XOptions = ((global::Gtk.AttachOptions)(4));
			w60.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry64 = new global::Gtk.Entry ();
			this.entry64.WidthRequest = 45;
			this.entry64.HeightRequest = 45;
			this.entry64.CanFocus = true;
			this.entry64.Name = "entry64";
			this.entry64.IsEditable = true;
			this.entry64.InvisibleChar = '•';
			this.table1.Add (this.entry64);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry64]));
			w61.TopAttach = ((uint)(7));
			w61.BottomAttach = ((uint)(8));
			w61.LeftAttach = ((uint)(6));
			w61.RightAttach = ((uint)(7));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry65 = new global::Gtk.Entry ();
			this.entry65.WidthRequest = 45;
			this.entry65.HeightRequest = 45;
			this.entry65.CanFocus = true;
			this.entry65.Name = "entry65";
			this.entry65.IsEditable = true;
			this.entry65.InvisibleChar = '•';
			this.table1.Add (this.entry65);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry65]));
			w62.TopAttach = ((uint)(8));
			w62.BottomAttach = ((uint)(9));
			w62.LeftAttach = ((uint)(6));
			w62.RightAttach = ((uint)(7));
			w62.XOptions = ((global::Gtk.AttachOptions)(4));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry66 = new global::Gtk.Entry ();
			this.entry66.WidthRequest = 45;
			this.entry66.HeightRequest = 45;
			this.entry66.CanFocus = true;
			this.entry66.Name = "entry66";
			this.entry66.IsEditable = true;
			this.entry66.InvisibleChar = '•';
			this.table1.Add (this.entry66);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry66]));
			w63.TopAttach = ((uint)(1));
			w63.BottomAttach = ((uint)(2));
			w63.LeftAttach = ((uint)(7));
			w63.RightAttach = ((uint)(8));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry67 = new global::Gtk.Entry ();
			this.entry67.WidthRequest = 45;
			this.entry67.HeightRequest = 45;
			this.entry67.CanFocus = true;
			this.entry67.Name = "entry67";
			this.entry67.IsEditable = true;
			this.entry67.InvisibleChar = '•';
			this.table1.Add (this.entry67);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry67]));
			w64.TopAttach = ((uint)(2));
			w64.BottomAttach = ((uint)(3));
			w64.LeftAttach = ((uint)(7));
			w64.RightAttach = ((uint)(8));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry68 = new global::Gtk.Entry ();
			this.entry68.WidthRequest = 45;
			this.entry68.HeightRequest = 45;
			this.entry68.CanFocus = true;
			this.entry68.Name = "entry68";
			this.entry68.IsEditable = true;
			this.entry68.InvisibleChar = '•';
			this.table1.Add (this.entry68);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry68]));
			w65.TopAttach = ((uint)(3));
			w65.BottomAttach = ((uint)(4));
			w65.LeftAttach = ((uint)(7));
			w65.RightAttach = ((uint)(8));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry69 = new global::Gtk.Entry ();
			this.entry69.WidthRequest = 45;
			this.entry69.HeightRequest = 45;
			this.entry69.CanFocus = true;
			this.entry69.Name = "entry69";
			this.entry69.IsEditable = true;
			this.entry69.InvisibleChar = '•';
			this.table1.Add (this.entry69);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry69]));
			w66.TopAttach = ((uint)(4));
			w66.BottomAttach = ((uint)(5));
			w66.LeftAttach = ((uint)(7));
			w66.RightAttach = ((uint)(8));
			w66.XOptions = ((global::Gtk.AttachOptions)(4));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry7 = new global::Gtk.Entry ();
			this.entry7.WidthRequest = 45;
			this.entry7.HeightRequest = 45;
			this.entry7.CanFocus = true;
			this.entry7.Name = "entry7";
			this.entry7.IsEditable = true;
			this.entry7.InvisibleChar = '•';
			this.table1.Add (this.entry7);
			global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry7]));
			w67.TopAttach = ((uint)(6));
			w67.BottomAttach = ((uint)(7));
			w67.XOptions = ((global::Gtk.AttachOptions)(4));
			w67.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry70 = new global::Gtk.Entry ();
			this.entry70.WidthRequest = 45;
			this.entry70.HeightRequest = 45;
			this.entry70.CanFocus = true;
			this.entry70.Name = "entry70";
			this.entry70.IsEditable = true;
			this.entry70.InvisibleChar = '•';
			this.table1.Add (this.entry70);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry70]));
			w68.TopAttach = ((uint)(5));
			w68.BottomAttach = ((uint)(6));
			w68.LeftAttach = ((uint)(7));
			w68.RightAttach = ((uint)(8));
			w68.XOptions = ((global::Gtk.AttachOptions)(4));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry71 = new global::Gtk.Entry ();
			this.entry71.WidthRequest = 45;
			this.entry71.HeightRequest = 45;
			this.entry71.CanFocus = true;
			this.entry71.Name = "entry71";
			this.entry71.IsEditable = true;
			this.entry71.InvisibleChar = '•';
			this.table1.Add (this.entry71);
			global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry71]));
			w69.TopAttach = ((uint)(6));
			w69.BottomAttach = ((uint)(7));
			w69.LeftAttach = ((uint)(7));
			w69.RightAttach = ((uint)(8));
			w69.XOptions = ((global::Gtk.AttachOptions)(4));
			w69.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry72 = new global::Gtk.Entry ();
			this.entry72.WidthRequest = 45;
			this.entry72.HeightRequest = 45;
			this.entry72.CanFocus = true;
			this.entry72.Name = "entry72";
			this.entry72.IsEditable = true;
			this.entry72.InvisibleChar = '•';
			this.table1.Add (this.entry72);
			global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry72]));
			w70.TopAttach = ((uint)(7));
			w70.BottomAttach = ((uint)(8));
			w70.LeftAttach = ((uint)(7));
			w70.RightAttach = ((uint)(8));
			w70.XOptions = ((global::Gtk.AttachOptions)(4));
			w70.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry73 = new global::Gtk.Entry ();
			this.entry73.WidthRequest = 45;
			this.entry73.HeightRequest = 45;
			this.entry73.CanFocus = true;
			this.entry73.Name = "entry73";
			this.entry73.IsEditable = true;
			this.entry73.InvisibleChar = '•';
			this.table1.Add (this.entry73);
			global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry73]));
			w71.TopAttach = ((uint)(8));
			w71.BottomAttach = ((uint)(9));
			w71.LeftAttach = ((uint)(7));
			w71.RightAttach = ((uint)(8));
			w71.XOptions = ((global::Gtk.AttachOptions)(4));
			w71.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry74 = new global::Gtk.Entry ();
			this.entry74.WidthRequest = 45;
			this.entry74.HeightRequest = 45;
			this.entry74.CanFocus = true;
			this.entry74.Name = "entry74";
			this.entry74.IsEditable = true;
			this.entry74.InvisibleChar = '•';
			this.table1.Add (this.entry74);
			global::Gtk.Table.TableChild w72 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry74]));
			w72.TopAttach = ((uint)(1));
			w72.BottomAttach = ((uint)(2));
			w72.LeftAttach = ((uint)(8));
			w72.RightAttach = ((uint)(9));
			w72.XOptions = ((global::Gtk.AttachOptions)(4));
			w72.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry75 = new global::Gtk.Entry ();
			this.entry75.WidthRequest = 45;
			this.entry75.HeightRequest = 45;
			this.entry75.CanFocus = true;
			this.entry75.Name = "entry75";
			this.entry75.IsEditable = true;
			this.entry75.InvisibleChar = '•';
			this.table1.Add (this.entry75);
			global::Gtk.Table.TableChild w73 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry75]));
			w73.TopAttach = ((uint)(2));
			w73.BottomAttach = ((uint)(3));
			w73.LeftAttach = ((uint)(8));
			w73.RightAttach = ((uint)(9));
			w73.XOptions = ((global::Gtk.AttachOptions)(4));
			w73.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry76 = new global::Gtk.Entry ();
			this.entry76.WidthRequest = 45;
			this.entry76.HeightRequest = 45;
			this.entry76.CanFocus = true;
			this.entry76.Name = "entry76";
			this.entry76.IsEditable = true;
			this.entry76.InvisibleChar = '•';
			this.table1.Add (this.entry76);
			global::Gtk.Table.TableChild w74 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry76]));
			w74.TopAttach = ((uint)(3));
			w74.BottomAttach = ((uint)(4));
			w74.LeftAttach = ((uint)(8));
			w74.RightAttach = ((uint)(9));
			w74.XOptions = ((global::Gtk.AttachOptions)(4));
			w74.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry77 = new global::Gtk.Entry ();
			this.entry77.WidthRequest = 45;
			this.entry77.HeightRequest = 45;
			this.entry77.CanFocus = true;
			this.entry77.Name = "entry77";
			this.entry77.IsEditable = true;
			this.entry77.InvisibleChar = '•';
			this.table1.Add (this.entry77);
			global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry77]));
			w75.TopAttach = ((uint)(4));
			w75.BottomAttach = ((uint)(5));
			w75.LeftAttach = ((uint)(8));
			w75.RightAttach = ((uint)(9));
			w75.XOptions = ((global::Gtk.AttachOptions)(4));
			w75.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry78 = new global::Gtk.Entry ();
			this.entry78.WidthRequest = 45;
			this.entry78.HeightRequest = 45;
			this.entry78.CanFocus = true;
			this.entry78.Name = "entry78";
			this.entry78.IsEditable = true;
			this.entry78.InvisibleChar = '•';
			this.table1.Add (this.entry78);
			global::Gtk.Table.TableChild w76 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry78]));
			w76.TopAttach = ((uint)(5));
			w76.BottomAttach = ((uint)(6));
			w76.LeftAttach = ((uint)(8));
			w76.RightAttach = ((uint)(9));
			w76.XOptions = ((global::Gtk.AttachOptions)(4));
			w76.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry79 = new global::Gtk.Entry ();
			this.entry79.WidthRequest = 45;
			this.entry79.HeightRequest = 45;
			this.entry79.CanFocus = true;
			this.entry79.Name = "entry79";
			this.entry79.IsEditable = true;
			this.entry79.InvisibleChar = '•';
			this.table1.Add (this.entry79);
			global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry79]));
			w77.TopAttach = ((uint)(6));
			w77.BottomAttach = ((uint)(7));
			w77.LeftAttach = ((uint)(8));
			w77.RightAttach = ((uint)(9));
			w77.XOptions = ((global::Gtk.AttachOptions)(4));
			w77.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry8 = new global::Gtk.Entry ();
			this.entry8.WidthRequest = 45;
			this.entry8.HeightRequest = 45;
			this.entry8.CanFocus = true;
			this.entry8.Name = "entry8";
			this.entry8.IsEditable = true;
			this.entry8.InvisibleChar = '•';
			this.table1.Add (this.entry8);
			global::Gtk.Table.TableChild w78 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry8]));
			w78.TopAttach = ((uint)(7));
			w78.BottomAttach = ((uint)(8));
			w78.XOptions = ((global::Gtk.AttachOptions)(4));
			w78.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry80 = new global::Gtk.Entry ();
			this.entry80.WidthRequest = 45;
			this.entry80.HeightRequest = 45;
			this.entry80.CanFocus = true;
			this.entry80.Name = "entry80";
			this.entry80.IsEditable = true;
			this.entry80.InvisibleChar = '•';
			this.table1.Add (this.entry80);
			global::Gtk.Table.TableChild w79 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry80]));
			w79.TopAttach = ((uint)(7));
			w79.BottomAttach = ((uint)(8));
			w79.LeftAttach = ((uint)(8));
			w79.RightAttach = ((uint)(9));
			w79.XOptions = ((global::Gtk.AttachOptions)(4));
			w79.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry81 = new global::Gtk.Entry ();
			this.entry81.WidthRequest = 45;
			this.entry81.HeightRequest = 45;
			this.entry81.CanFocus = true;
			this.entry81.Name = "entry81";
			this.entry81.IsEditable = true;
			this.entry81.InvisibleChar = '•';
			this.table1.Add (this.entry81);
			global::Gtk.Table.TableChild w80 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry81]));
			w80.TopAttach = ((uint)(8));
			w80.BottomAttach = ((uint)(9));
			w80.LeftAttach = ((uint)(8));
			w80.RightAttach = ((uint)(9));
			w80.XOptions = ((global::Gtk.AttachOptions)(4));
			w80.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry9 = new global::Gtk.Entry ();
			this.entry9.WidthRequest = 45;
			this.entry9.HeightRequest = 45;
			this.entry9.CanFocus = true;
			this.entry9.Name = "entry9";
			this.entry9.IsEditable = true;
			this.entry9.InvisibleChar = '•';
			this.table1.Add (this.entry9);
			global::Gtk.Table.TableChild w81 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry9]));
			w81.TopAttach = ((uint)(8));
			w81.BottomAttach = ((uint)(9));
			w81.XOptions = ((global::Gtk.AttachOptions)(4));
			w81.YOptions = ((global::Gtk.AttachOptions)(4));
			this.fixed2.Add (this.table1);
			global::Gtk.Fixed.FixedChild w82 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.table1]));
			w82.X = 105;
			w82.Y = 107;
			this.Add (this.fixed2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 600;
			this.DefaultHeight = 600;
			this.Show ();
		}
	}
}
